apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-app
spec:
  containers:
    - name: mysql-container
      image: mysql:5
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: geek
          